INSERT INTO `studenti3` (`id`, `nome`, `cognome`, `genere`, `indirizzo`, `citta`, `provincia`, `regione`, `email`, `data_nascita`) VALUES
(1, 'Luca', 'Rossi', 'm', 'Via Roma 1', 'Torino', 'TO', 'Piemonte', 'luca.rossi@email.com', '2000-01-15'),
(2, 'Maria', 'Bianchi', 'f', 'Corso Italia 10', 'Milano', 'MI', 'Lombardia', 'maria.bianchi@email.com', '2001-03-22'),
(3, 'Giovanni', 'Verdi', 'm', 'Piazza Repubblica 5', 'Novara', 'NO', 'Piemonte', 'giovanni.verdi@email.com', '1999-11-08'),
(4, 'Anna', 'Neri', 'f', 'Via Garibaldi 20', 'Bergamo', 'BG', 'Lombardia', 'anna.neri@email.com', '2002-06-30'),
(5, 'Paolo', 'Gialli', 'm', 'Viale Dante 15', 'Asti', 'AT', 'Piemonte', 'paolo.gialli@email.com', '2000-09-12'),
(6, 'Laura', 'Blu', 'f', 'Via Torino 30', 'Brescia', 'BS', 'Lombardia', 'laura.blu@email.com', '2001-04-05'),
(7, 'Marco', 'Viola', 'm', 'Corso Mazzini 25', 'Alessandria', 'AL', 'Piemonte', 'marco.viola@email.com', '1998-12-28'),
(8, 'Elena', 'Arancio', 'f', 'Piazza Venezia 8', 'Como', 'CO', 'Lombardia', 'elena.arancio@email.com', '2003-02-18'),
(9, 'Simone', 'Marrone', 'm', 'Via Cavour 12', 'Vercelli', 'VC', 'Piemonte', 'simone.marrone@email.com', '2000-07-25'),
(10, 'Sara', 'Grigio', 'f', 'Viale Vittorio Veneto 18', 'Cremona', 'CR', 'Lombardia', 'sara.grigio@email.com', '2001-10-03'),
(11, 'Andrea', 'Rosa', 'm', 'Via Nazionale 35', 'Cuneo', 'CN', 'Piemonte', 'andrea.rosa@email.com', '1999-05-10'),
(12, 'Francesca', 'Azzurro', 'f', 'Corso Umberto I 50', 'Lecco', 'LC', 'Lombardia', 'francesca.azzurro@email.com', '2002-08-20'),
(13, 'Davide', 'Oro', 'm', 'Piazza Duomo 40', 'Biella', 'BI', 'Piemonte', 'davide.oro@email.com', '2000-12-01'),
(14, 'Giulia', 'Argento', 'f', 'Via Indipendenza 45', 'Lodi', 'LO', 'Lombardia', 'giulia.argento@email.com', '2001-07-15'),
(15, 'Alessio', 'Bronzo', 'm', 'Viale Regina Margherita 60', 'Verbania', 'VB', 'Piemonte', 'alessio.bronzo@email.com', '1998-09-27'),
(16, 'Chiara', 'Rame', 'f', 'Corso Buenos Aires 70', 'Mantova', 'MN', 'Lombardia', 'chiara.rame@email.com', '2003-01-05'),
(17, 'Riccardo', 'Ferro', 'm', 'Via XX Settembre 75', 'Torino', 'TO', 'Piemonte', 'riccardo.ferro@email.com', '2000-04-18'),
(18, 'Martina', 'Stagno', 'f', 'Piazza Castello 80', 'Monza', 'MB', 'Lombardia', 'martina.stagno@email.com', '2001-11-28'),
(19, 'Gabriele', 'Piombo', 'm', 'Viale Monza 85', 'Novara', 'NO', 'Piemonte', 'gabriele.piombo@email.com', '1999-08-03'),
(20, 'Federica', 'Zinco', 'f', 'Via Dante Alighieri 90', 'Pavia', 'PV', 'Lombardia', 'federica.zinco@email.com', '2002-03-12'),
(21, 'Mattia', 'Platino', 'm', 'Corso Vittorio Emanuele II 95', 'Asti', 'AT', 'Piemonte', 'mattia.platino@email.com', '2000-06-20'),
(22, 'Valentina', 'Titanio', 'f', 'Piazza Garibaldi 100', 'Sondrio', 'SO', 'Lombardia', 'valentina.titanio@email.com', '2001-09-08'),
(23, 'Lorenzo', 'Cobalto', 'm', 'Via Roma 105', 'Alessandria', 'AL', 'Piemonte', 'lorenzo.cobalto@email.com', '1998-12-15'),
(24, 'Beatrice', 'Nichel', 'f', 'Viale Repubblica 110', 'Varese', 'VA', 'Lombardia', 'beatrice.nichel@email.com', '2003-05-25'),
(25, 'Edoardo', 'Cromo', 'm', 'Corso Italia 115', 'Vercelli', 'VC', 'Piemonte', 'edoardo.cromo@email.com', '2000-08-01'),
(26, 'Alessandra', 'Vanadio', 'f', 'Piazza Mazzini 120', 'Milano', 'MI', 'Lombardia', 'alessandra.vanadio@email.com', '2001-02-10'),
(27, 'Leonardo', 'Tungsteno', 'm', 'Via Garibaldi 125', 'Cuneo', 'CN', 'Piemonte', 'leonardo.tungsteno@email.com', '1999-10-18'),
(28, 'Sofia', 'Molibdeno', 'f', 'Viale Dante 130', 'Brescia', 'BS', 'Lombardia', 'sofia.molibdeno@email.com', '2002-07-03'),
(29, 'Tommaso', 'Manganese', 'm', 'Via Torino 135', 'Biella', 'BI', 'Piemonte', 'tommaso.manganese@email.com', '2000-11-22'),
(30, 'Giorgia', 'Iridio', 'f', 'Corso Mazzini 140', 'Bergamo', 'BG', 'Lombardia', 'giorgia.iridio@email.com', '2001-04-29');
